## Kalman filters
Kalman filters are a way of quantifying uncertainty surrounding the internal state of a dynamical system from a noisey signal. Algorithm works in two phases:
1. *Prediction phase*: estimate the current state variables and related uncertainties. 
2. *Update estimate*: take weighted average of state observation and estimate. Larger weight is given to estimates with greater certainty. 

A **state extrapolation** function is produced which is of the form of classic control:
$$ \hat{x}_{n+1,n} = F\hat{x}_{n,n}  + G u_{n} + w_{n} $$ 

In the above, matrices F and G are to be estimated from the **state space**, differential equations. 
$$ \dot{x(t)} = Ax(t) + Bu(t) $$
$$ \dot{y(t)} = Cx(t) + Du(t) $$ 

Distinguishing the differerence between **state extrapolation** and **state space**, the former has output of the same units whereas **state space** are differential equations.


Steps involved in derving the *state dynamics matrix*:
1. Set up *governing equation*, u which is the sum of derivate
2. Isolate the highest order derivative, $\frac{d^{n}x}{dt^n} = \frac{d^{n-1}x}{dt^n-1} + \frac{dx}{dt} + u$
3. Set system of equations where $x_{x+1} = \frac{d^n}{dt^{n}}$
4. Set highest $x_{n+1}$ term to $\frac{d^{n-1}x}{dt^n-1} + \frac{dx}{dt} + u$
5. Express this in matrix form $ \dot{x(t)} = Ax(t) + Bu(t) $


Note: to form the weighted sum in uncertainty, the Kalman filter assumes noise to be present in both the *prediction* and *measurement*. The Kalman filter propagates uncertainty recursively and has significant parallels to Bayesian updating.

Higher order dynamical systems can be restructured into 'first order differential equations' by defining new variables and substituting higher order terms. 


What is the state dynamics matrix? A
What is the state transition matrix? F

### Kalman filters

#### Kalman gain
The Kalman gain, K, is used to determine how much of the new measurements to use to update the new estimate. The Kalman Gain is bound between zero and one; \[0,1\]. In essence the Kalman gain is an proportion of error in the estimate compared to measurement. The Kalman Gain is then used to calculate the new estimate which is given by
$$ Est_t = Est_{t-1} + K[Meas - Est_{t-1}] $$ 

When K is close to zero the estimate is stable and measurements are inaccurate, whereas when K is close to 1 difference between measurement and prediction will have large effects on the update. 

#### State matrix
Keeps track of underlyng system dynamics such as position and velocity.

#### Observation matrix
Extracts key variables from process?

#### State covariance and measurement covariance matrices

### Questions: 
Why is the Kalman filter known as a Mean Square Error fit to measurements? 
How is covariance update derived from matrix form? Relies on quadratic form of matrix; why is this equal to the variance? (*Answers in [detailed derivations]*)

Why is '(np.diag(np.ones(len(X))) - kalman_gain.dot(H)).dot(P).dot((np.diag(np.ones(len(X))) + kalman_gain.dot(H)).T) - kalman_gain.dot(R).dot(kalman_gain.T)' equal to $P = (I - KH)P^p$

#### Examples of Kalman filters

## Bibliography/references
[Detailed intro](https://www.kalmanfilter.net/multiExamples.html) 

[Code inspiration](https://medium.com/@jaems33/understanding-kalman-filters-with-python-2310e87b8f48)

[Detailed derivations](https://web.mit.edu/kirtley/kirtley/binlustuff/literature/control/Kalman%20filter.pdf)

### Codified Kalman filter
Below is an example of a Kalman filter codified. Note the State Extrapoloation matrix is assumed as pre-calculated. Therefore the differential equations involved in the System State Representation equations have already been solved and formed into required matrices. 

In [1]:
import numpy as np
from numpy.linalg import inv

x_observations = np.array([4000, 4260, 4550, 4860, 5110])
v_observations = np.array([280, 282, 285, 286, 290])

z = np.c_[x_observations, v_observations]

# Initial Conditions
a = 2  # Acceleration
v = 280
t = 1  # Difference in time

# Process / Estimation Errors
error_est_x = 20
error_est_v = 5

# Observation Errors
error_obs_x = 25  # Uncertainty in the measurement
error_obs_v = 6

def prediction2d(x, v, t, a):
    A = np.array([[1, t],
                  [0, 1]])
    X = np.array([[x],
                  [v]])
    B = np.array([[0.5 * t ** 2],
                  [t]])
    X_prime = A.dot(X) + B.dot(a)
    return X_prime


def covariance2d(sigma1, sigma2):
    cov1_2 = sigma1 * sigma2
    cov2_1 = sigma2 * sigma1
    cov_matrix = np.array([[sigma1 ** 2, cov1_2],
                           [cov2_1, sigma2 ** 2]])
    return np.diag(np.diag(cov_matrix))


# Initial Estimation Covariance Matrix
P = covariance2d(error_est_x, error_est_v)
A = np.array([[1, t],
              [0, 1]])

# Initial State Matrix
X = np.array([[z[0][0]],
              [v]])
n = len(z[0])

for data in z[1:]:
    X = prediction2d(X[0][0], X[1][0], t, a)
    # To simplify the problem, professor
    # set off-diagonal terms to 0.
    P = np.diag(np.diag(A.dot(P).dot(A.T)))

    # Calculating the Kalman Gain
    H = np.identity(n)
    R = covariance2d(error_obs_x, error_obs_v)
    S = H.dot(P).dot(H.T) + R
    K = P.dot(H).dot(inv(S))

    # Reshape the new data into the measurement space.
    Y = H.dot(data).reshape(n, -1)

    # Update the State Matrix
    # Combination of the predicted state, measured values, covariance matrix and Kalman Gain
    X = X + K.dot(Y - H.dot(X))

    # Update Process Covariance Matrix
    P = (np.identity(len(K)) - K.dot(H)).dot(P)

print("Kalman Filter State Matrix:\n", X)

Kalman Filter State Matrix:
 [[5127.05898493]
 [ 288.55147059]]


### Example with car accelerating in x dimensional space.

In [82]:
observations_x = [-393.66, -375.93-351.04,-328.96,-299.35,-273.36,-245.89,-222.58,-198.03,-174.17,-146.32,-123.72,-103.47,-78.23,-52.63,-23.34,25.96,49.72,76.94,95.38,119.83,144.01,161.84,180.56,201.42,222.62,239.4,252.51,266.26,271.75,277.4,294.12,301.23,291.8,299.89]



def prediction3d(X,t, a):
    A = np.array([[1, t, 0.5*t**2],
                  [0, 1, t], 
                  [0, 0, 1]])

    B = np.array([[0.5 * t ** 2],
                  [t]])
    X_prime = A.dot(X) # + B.dot(a)
    return X_prime

def covariance3d(P,t,a):
    # calculates FXF^T + Q
    A = np.array([[1, t, 0.5*t**2],
                  [0, 1, t], 
                  
                  [0, 0, 1]])
    
    Q = np.array([[t**4/4, t**3/3, t**2/2],
                  [t**3/2, t**2, t], 
                  [t**2, t, 1]])
    return A.dot(P).dot(A.T) + Q*a**2

def kalman_gain_calc(P,h,r):
    H = np.array([h])
    R = np.array([r])
    return P.dot(H.T).dot(inv(H.dot(P).dot(H.T) + R))


def update_state(current_state, kalman_gain, h, obs): 
    H = np.array([h])
    return current_state + kalman_gain.dot(obs - H.dot(current_state))


def update_covariance(P, kalman_gain, h, r):
    H = np.array([h])
    R = np.array([r])
    return (np.diag(np.ones(len(X))) - kalman_gain.dot(H)).dot(P).dot((np.diag(np.ones(len(X))) + kalman_gain.dot(H)).T) + kalman_gain.dot(R).dot(kalman_gain.T)
    

In [85]:
X = np.array([[0],
              [0],
              [0]])

P = np.diag([500,500,500])

for obs in observations_x:
    # predict next state and covariance 
    X_tplus1 = prediction3d(X,1,1)
    P_tplus1 = covariance3d(P,1,0.2)
    print(f'next state \n {X_tplus1}')
    print(f'covariance \n {P_tplus1}')

    # calculate kalman gain
    kalman_gain_ = kalman_gain_calc(P_tplus1, [1,0,0], [3])
    print(f'kalman gain \n {kalman_gain_}')

    # record observation
    X = update_state(X_tplus1, kalman_gain_, [1,0,0], obs)
    P = update_covariance(P_tplus1, kalman_gain_, [1,0,0], [3])
    break
print(X)
print(P)

next state 
 [[0.]
 [0.]
 [0.]]
covariance 
 [[1125.01        750.01333333  250.02      ]
 [ 750.02       1000.04        500.04      ]
 [ 250.04        500.04        500.04      ]]
kalman gain 
 [[0.99734045]
 [0.66490545]
 [0.2216647 ]]
[[-392.6130412 ]
 [-261.74668061]
 [ -87.26052641]]
[[  8.96014918   5.97352125   1.99139195]
 [  5.97353898 504.00464044 334.68465506]
 [  1.99144514 334.67283472 444.91420276]]


In [56]:
update_covariance(P, kalman_gain_, [1,0,0])

array([[  2.99202135,   1.99469863,   0.66494091],
       [  1.99471636, 501.35204487, 333.80033865],
       [  0.6649941 , 333.78851831, 444.61939132]])

In [66]:
update_covariance(P, kalman_gain_, [1,0,0], [3])

array([[  2.99202135,   1.99469863,   0.66494091],
       [  1.99471636, 501.35204487, 333.80033865],
       [  0.6649941 , 333.78851831, 444.61939132]])